apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fidelidade
  namespace: argocd
spec:
  project: default
  source:    
      repoURL: https://github.com/olivomarco/test-fidelidade2.git
      targetRevision: HEAD
      path: kustomize/overlays/dev
  syncPolicy:
      automated: {}
  destination:
      namespace: argocd
      server: https://kubernetes.default.svc
  #template:
  #  metadata:
  #    annotations:
  #      backstage.io/kubernetes-id: fidelidade
