apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2svc
  namespace: argocd
spec:
  project: default
  source:    
      repoURL: https://github.com/olivomarco/demo2code.git
      targetRevision: HEAD
      path: kustomize/overlays/dev
  syncPolicy:
      automated: {}
  destination:
      namespace: argocd
      server: https://kubernetes.default.svc
  # template:
  #   metadata:
  #     annotations:
  #       backstage.io/kubernetes-id: demo2svc
