namespace: fidelidade-cluster-cluster-dev

resources:
- ../base
- namespace.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: cluster-claim-patch.yaml
- path: resource-group-patch.yaml
