apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "fidelidade-cluster"
spec:
  type: kubernetes-cluster
  owner: user:guest
  lifecycle: experimental
  providesApis: [example-grpc-api]